Build Error
C:/Users/yide4/.cargo/bin/cargo.exe build --color=always --message-format=json-diagnostic-rendered-ansi --package rust-ffi-cpp --bin rust-ffi-cpp
   Compiling ffi_cpp v0.1.0 (C:\Users\yide4\CLionProjects\rust-ffi-cpp\lib\ffi_cpp)
error: failed to run custom build command for `ffi_cpp v0.1.0 (C:\Users\yide4\CLionProjects\rust-ffi-cpp\lib\ffi_cpp)`
Caused by:
  process didn't exit successfully: `C:\Users\yide4\CLionProjects\rust-ffi-cpp\target\debug\build\ffi_cpp-632d523dc43ea7f0\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  --- stderr
  thread 'main' panicked at '
  couldn't determine visual studio generator
  if VisualStudio is installed, however, consider running the appropriate vcvars script before building this crate
  ', C:\Users\yide4\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.46\src\lib.rs:877:25
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
     1: std::panicking::begin_panic_fmt
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:460
     2: cmake::Config::visual_studio_generator
               at C:\Users\yide4\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.46\src\lib.rs:877
     3: cmake::Config::build
               at C:\Users\yide4\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.46\src\lib.rs:587
     4: cmake::build<str>
               at C:\Users\yide4\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.46\src\lib.rs:105
     5: build_script_build::main
               at .\build.rs:6
     6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Process finished with exit code 101